image: composer:2

pipelines:
    default:
        - step:
            caches:
                - composer
                - builddir
            script:
                - composer install --no-progress --no-scripts --ignore-platform-reqs
                - composer run check
definitions:
    caches:
        builddir: .Build

